[package]
name = "perceptron_iris"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.21", features = ["train", "wgpu"] }
csv = "1.4.0"
iced = "0.14.0"
image = "0.25.10"
polars = { version = "0.38", features = ["lazy", "csv"] }
rerun = "0.35.0"
strum = "0.28.0"
strum_macros = "0.28.0"

